### Bayes' Theorem Implementation

In [5]:
def bayes_theorem(p_disease, p_symptom_given_disease, p_symptom):
  p_disease_given_symptom = (p_disease * p_symptom_given_disease) / p_symptom
  return p_disease_given_symptom

p_disease = 0.01  
p_symptom_given_disease = 0.8  
p_symptom = 0.1 

posterior_probability = bayes_theorem(p_disease, p_symptom_given_disease, p_symptom)
print("Posterior probability of the disease given the symptom:", posterior_probability)


Posterior probability of the disease given the symptom: 0.08


### Eigenvalues and Eigenvectors of a Matrix

In [2]:
import numpy as np

A = np.array([[4, 1], [2, 3]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


### Determinant and Inverse of a 3x3 Matrix

In [3]:
B = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])


det_B = np.linalg.det(B)

if det_B != 0:
    inv_B = np.linalg.inv(B)
    print("Determinant of B:", det_B)
    print("Inverse of B:\n", inv_B)
else:
    print("Matrix B is singular and does not have an inverse.")


Determinant of B: 0.9999999999999964
Inverse of B:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


### Properties of the Normal Distribution

In [4]:
'''
Symmetry: The normal distribution is symmetric about the mean.

Mean, Median, and Mode: All are equal in a normal distribution.

68-95-99.7 Rule: Approximately 68% of the data falls within one standard deviation of the mean, 95% within two, and 99.7% within three.

Asymptotic: The tails of the distribution approach the horizontal axis but never touch it.
'''

'\nSymmetry: The normal distribution is symmetric about the mean.\n\nMean, Median, and Mode: All are equal in a normal distribution.\n\n68-95-99.7 Rule: Approximately 68% of the data falls within one standard deviation of the mean, 95% within two, and 99.7% within three.\n\nAsymptotic: The tails of the distribution approach the horizontal axis but never touch it.\n'

### Applications of the Normal Distribution

In [ ]:
'''
Natural and Social Sciences: Modeling phenomena like heights, test scores, etc.

Finance: Modeling stock returns.

Quality Control: Assessing variation in manufacturing.
'''