In [1]:
import numpy as np

### Defining Matrices

In [35]:
a = np.array([[3,4,2],
             [8,3,5],
             [6,6,7]])


b = np.random.randint(1,10, size=(3,3))

print("Matrix A is: \n", a)
print("\n\nMatrix B is: \n", b)

Matrix A is: 
 [[3 4 2]
 [8 3 5]
 [6 6 7]]


Matrix B is: 
 [[4 9 1]
 [1 5 2]
 [7 5 9]]


### Matrix Multiplication

In [36]:
c = np.matmul(a,b)
print("The Matrix Mutliplication of matrix A and B is: \n", c)

The Matrix Mutliplication of matrix A and B is: 
 [[ 30  57  29]
 [ 70 112  59]
 [ 79 119  81]]


### Matrix Transpose

In [37]:
t = np.transpose(a)
print("Matrix A:\n", a)
print("\nTranspose of A: \n", t)

Matrix A:
 [[3 4 2]
 [8 3 5]
 [6 6 7]]

Transpose of A: 
 [[3 8 6]
 [4 3 6]
 [2 5 7]]


### Matrix Determinant

In [38]:
d = np.linalg.det(a)
print("Matrix A:\n", a)
print("\nDeterminant of A is: ", round(d))

Matrix A:
 [[3 4 2]
 [8 3 5]
 [6 6 7]]

Determinant of A is:  -71


### Eigen Vectors

In [39]:
eigen = np.linalg.eig(a)

print("Eigne values are: \n", eigen[0])

eVec = eigen[1]
rounded_eVec = np.round(eVec, decimals=2)
print("\nEigen Vectors are: \n", rounded_eVec)

Eigne values are: 
 [14.26352157  1.68704377 -2.95056534]

Eigen Vectors are: 
 [[-0.34 -0.48  0.5 ]
 [-0.57 -0.26 -0.84]
 [-0.75  0.84  0.21]]
